### ISSUE TITLE
issue with Drosophila in ott2.8

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/reference-taxonomy#112]
While using a new tutorial in peyotl to test things I notices 2 genera in animals with the name Drosophila (based on the tnrs/match_names call and then taxonomy/taxon for info on the ancestral taxon).

The IDs are 5554385 and 34907

info on one (coming from taxonomy/taxon):

    $ python tutorials/ot-taxon-info.py --include-lineage 5554385 
    Taxon info for OTT ID (ot:ottId) = 5554385
        name (ot:ottTaxonName) = "Drosophila"
        known synonyms: "Hypenomyia", "Drosophila"
        OTT flags for this taxon: [u'EDITED', u'SIBLING_HIGHER', u'TATTERED', u'SIBLING_LOWER']
        The taxonomic rank associated with this name is: genus
        The (unstable) node ID in the current taxomachine instance is: 1842811
    Taxon 5554385 is a child of 34905.
    Taxon info for OTT ID (ot:ottId) = 34905
        name (ot:ottTaxonName) = "Drosophilidae"
        known synonyms: 
        OTT flags for this taxon: [u'EDITED']
        The taxonomic rank associated with this name is: family
        The (unstable) node ID in the current taxomachine instance is: 1836105
    ...

and for the other:

    $ python tutorials/ot-taxon-info.py --include-lineage 34907
    Taxon info for OTT ID (ot:ottId) = 34907
        name (ot:ottTaxonName) = "Drosophila"
        known synonyms: "Phloridosa", "Chusqueophila", "Psilodorha", "Siphlodora", "Hypenomyia", "Acrodrosophila", "Sordophila", "Spinodrosophila", "Dudaica", "Acanthopterna", "Acanthophila", "Chaetodrosophila", "Trichotobregma", "Chatodrosophilella", "Engiscaptomyza", "fruit fly", "Spinulophila", "fruit flies", "Drosophila"
        OTT flags for this taxon: []
        The taxonomic rank associated with this name is: genus
        The (unstable) node ID in the current taxomachine instance is: 1838729
    Taxon 34907 is a child of 1069157.
    Taxon info for OTT ID (ot:ottId) = 1069157
        name (ot:ottTaxonName) = "Drosophiliti"
        known synonyms: 
        OTT flags for this taxon: []
        The taxonomic rank associated with this name is: no rank
        The (unstable) node ID in the current taxomachine instance is: 1837343
    Taxon 1069157 is a child of 251315.
    Taxon info for OTT ID (ot:ottId) = 251315
        name (ot:ottTaxonName) = "Drosophilina"
        known synonyms: 
        OTT flags for this taxon: []
        The taxonomic rank associated with this name is: subtribe
        The (unstable) node ID in the current taxomachine instance is: 1837342
    Taxon 251315 is a child of 396616.
    Taxon info for OTT ID (ot:ottId) = 396616
        name (ot:ottTaxonName) = "Drosophilini"
        known synonyms: 
        OTT flags for this taxon: []
        The taxonomic rank associated with this name is: tribe
        The (unstable) node ID in the current taxomachine instance is: 1837304
    Taxon 396616 is a child of 127994.
    Taxon info for OTT ID (ot:ottId) = 127994
        name (ot:ottTaxonName) = "Drosophilinae"
        known synonyms: 
        OTT flags for this taxon: [u'SIBLING_LOWER']
        The taxonomic rank associated with this name is: subfamily
        The (unstable) node ID in the current taxomachine instance is: 1837303
    Taxon 127994 is a child of 34905.
    Taxon info for OTT ID (ot:ottId) = 34905
        name (ot:ottTaxonName) = "Drosophilidae"
        known synonyms: 
        OTT flags for this taxon: [u'EDITED']
        The taxonomic rank associated with this name is: family
        The (unstable) node ID in the current taxomachine instance is: 1836105
    ...

**Comment by jar398** [comment]
Using a slightly more recent version of IRMNG, this problem goes away - 34905 no longer occurs in OTT 2.9, and fortunately no studies reference that id.

**Comment by jar398** [comment]
There ought to be a test for this

**Comment by jar398** [comment]
```python tutorials/ot-taxon-info.py --include-lineage 5554385
the ott id 5554385 could not be found.```
