### ISSUE TITLE
Extinct taxa (Mycosphaeroides et al.)

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/reference-taxonomy#116]
From hyanwong:
Mycosphaeroides  https://github.com/OpenTreeOfLife/feedback/issues/54
Majasphaeridium   https://github.com/OpenTreeOfLife/feedback/issues/55
Griphopithecus  https://github.com/OpenTreeOfLife/feedback/issues/53

**Comment by hyanwong** [comment]
Also Rissoina bonneti, https://tree.opentreeoflife.org/opentree/argus/ottol@2892463/Rissoina-bonneti
