### ISSUE TITLE
broken link on http://files.opentreeoflife.org/ott/

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/reference-taxonomy#124]
The download link at http://files.opentreeoflife.org/ott/ott2.8/  for the reference taxonomy v2.8 is broken. (links to http://purl.org/ott/ott2.8/ott2.8.tgz)

**Comment by jar398** [comment]
OK, I know what this is; it seems other people are following my
instructions for modifying the files site but I'm not.  Will fix.

**Comment by jar398** [comment]
Try again now.

**Comment by snacktavish** [comment]
Fixed!
