### ISSUE TITLE
Documentation of what flags mean

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/reference-taxonomy#129]
Little to no information exists as to what the different OTT flags mean. The [wiki page](https://github.com/OpenTreeOfLife/reference-taxonomy/wiki/taxon-flags) points to [taxomachine code] (https://github.com/OpenTreeOfLife/taxomachine/blob/master/src/main/java/org/opentree/taxonomy/OTTFlag.java), but little information exists there.

Came up because a paleo person was trying to understand "extinct_direct" vs. "extinct_inherited".

**Comment by josephwb** [comment]
Can we make this a priority? I don't believe there even exists a complete list of flags. We need this for moving forward with the next synthesis.

**Comment by jar398** [comment]
Please review https://github.com/OpenTreeOfLife/reference-taxonomy/wiki/Taxon-flags

**Comment by josephwb** [comment]
Much better!

"merged" probably needs a bit of extra information.
"unplaced" is a bit of a head-scratcher. so, do we _not_ want to include them? may be good species (or whatever), just of unknown placement. i guess the same goes for "incertae sedis": there are certainly real bird species without known taxonomic/phylogenetic relationships.

**Comment by jar398** [comment]
On Wed, Aug 12, 2015 at 12:27 PM, Joseph W. Brown <notifications@github.com>
wrote:

> Much better!
>
> "merged" probably needs a bit of extra information.
>
will get on it.

> "unplaced" is a bit of a head-scratcher. so, do we *not* want to include
> them? may be good species (or whatever), just of unknown placement. i guess
> the same goes for "incertae sedis": there are certainly real bird species
> without known taxonomic/phylogenetic relationships.
>
I've been saying this for years now. Stephen has always said they couldn't
be included, but I never understood why.
