### ISSUE TITLE
taxon in taxonomy.tsv and synonyms.tsv

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/reference-taxonomy#132]
this may be a feature, but it surprised me. It is certainly possible for a name to be a junior synonym of another and a valid name depending on different classifications.

However I thought of ott as a classification rather than a full statement of synonomy. I was expecting, that smasher decided that a genus was in the classification then that genus name would not be in the synonyms file.  Are my expectations out of whack, or is this evidence of a bug?

In ott2.8 *Leucocarbo* is a genus name (of a tattered taxon) in taxonomy.tsv and also listed as a synonym for *Phalacrocorax*  

here it is in the taxon file (with 2 children)

    $ grep Leucocarbo ../../ott/ott2.8/taxonomy.tsv 
    3600667 |   969838  |   Leucocarbo  |   genus   |   gbif:4848922    |   Leucocarbo (genus gbif:4848922 in family Phalacrocoracidae) |tattered   |   
    3600684 |   3600667 |   Leucocarbo carunculatus |   species |   gbif:4848924,irmng:10442841 |       |   tattered_inherited  |
    3600687 |   3600667 |   Leucocarbo verrucosus   |   species |   gbif:6066497,irmng:10456104 |       |   tattered_inherited  |

here it are the hits for it in the synonmys file:

    $ grep Leucocarbo ../../ott/ott2.8/synonyms.tsv 
    Leucocarbo colensoi |   31563   |       |   Leucocarbo colensoi (synonym for Phalacrocorax colensoi)    |   
    Leucocarbo bougainvillii    |   9834    |       |   Leucocarbo bougainvillii (synonym for Phalacrocorax bougainvillii)  |   
    Leucocarbo atriceps |   446659  |       |   Leucocarbo atriceps (synonym for Phalacrocorax atriceps)    |   
    Leucocarbo chalconotus  |   480890  |       |   Leucocarbo chalconotus (synonym for Phalacrocorax chalconotus)  |   
    Phalacrocorax carunculatus  |   3600684 |       |   Phalacrocorax carunculatus (synonym for Leucocarbo carunculatus)    |   
    Leucocarbo campbelli    |   9831    |       |   Leucocarbo campbelli (synonym for Phalacrocorax campbelli)  |   
    Leucocarbo  |   322277  |       |   Leucocarbo (synonym for Phalacrocorax)  |   
    Leucocarbo albiventer   |   969843  |       |   Leucocarbo albiventer (synonym for Phalacrocorax albiventer)    |   
    Leucocarbo ranfurlyi    |   31566   |       |   Leucocarbo ranfurlyi (synonym for Phalacrocorax ranfurlyi)  |   
    Leucocarbo onslowi  |   9837    |       |   Leucocarbo onslowi (synonym for Phalacrocorax onslowi)  |   
    Phalacrocorax verrucosus    |   3600687 |       |   Phalacrocorax verrucosus (synonym for Leucocarbo verrucosus)    |   
    Leucocarbo punctatus    |   480891  |       |   Leucocarbo punctatus (synonym for Phalacrocorax punctatus)  |   

here is the taxon that it is synonym for:

    $ grep -e ^322277\\s ../../ott/ott2.8/taxonomy.tsv 
    322277  |   969838  |   Phalacrocorax   |   genus   |   ncbi:9207,gbif:2481854,irmng:1026979    |       |       |   

For what it is worth, my (very cursory) look around (e.g. http://en.wikipedia.org/wiki/Cormorant#Systematics ) seems to indicate that our current adoption of genbank usage of Phalacrocorax for all species in GenBank, but Leucocarbo for others generates a classification that would not please anyone.

**Comment by jar398** [comment]
Looks like a bug. I'll have to track it down. Synonym processing is extremely unsophisticated right now.

Relates to #113.

**Comment by jar398** [comment]
In OTT 2.9 these two genera both look fine to me. Both genera show up as non-tattered (i.e. merged between NCBI / GBIF, etc, no inconsistencies) in all three taxonomies. And neither genus name shows up as a synonym in NCBI, GBIF, or OTT.

If there had been a synonym record, it would have been in NCBI, saying that its Leuco was a synonym for its Phala.  In mapping GBIF to NCBI, GBIF Leuco probably did not map to NCBI Phala because another genus (namely GBIF Phala) already mapped to it.

I have made a change to the mapping logic, which is that (unlike in the OTT 2.8 smasher) you can now have two taxa from a source taxonomy map to the same taxon in OTT. Had this been in place for OTT 2.8, I'm pretty sure this problem wouldn't have come up.

**Comment by jar398** [comment]
You ask: "However I thought of ott as a classification rather than a full statement of synonomy. I was expecting, that smasher decided that a genus was in the classification then that genus name would not be in the synonyms file. Are my expectations out of whack, or is this evidence of a bug?"

I thought about this a bit. A major use case for OTT's synonyms table is OTU mapping and TNRS. We want to make OTU mapping as easy as possible, and therefore work as hard as possible to map a name to the right taxon. If the name in the study is Hyla, and there is a taxon Hyla along with two synonyms, then it may be the case that one of the synonyms is the correct match. It's easy enough for the user to ignore the synonyms, but the consequences of making the wrong assignment based on an incorrect unique match would be pretty bad.

This happens when the name and the synonym are in different parts of the tree, e.g. an insect and a mammal. We can also see it when the two taxa are close and probably ought to be merged but smasher thinks it doesn't have enough evidence to do so (no members in common, etc.).

**Comment by jar398** [comment]
Looks like I added a rule that says don't add a synonym X if there is already *any* taxon with name X in the taxonomy:

https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/org/opentreeoflife/smasher/Taxonomy.java#L988

That may be too strict, and may lead to unambiguous TNRS hits that really ought to be treated as ambiguous (perhaps the study really was using the name in the sense of the synonym; the curator will never know that the 'exact match' was to something else).

Here are the Leucocarbo results for OTT 2.9 draft 12. The synonym seems to have disappeared (perhaps an NCBI curator had second thoughts).

    bash-3.2$ grep Leucocarbo tax/ott/taxonomy.tsv 
    3600667	|	969838	|	Leucocarbo	|	genus	|	ncbi:1523025,gbif:4848922	|		|	sibling_higher	|	
    9837	|	3600667	|	Leucocarbo onslowi	|	species	|	ncbi:146615,worms:343949,gbif:4848926,irmng:10443128,irmng:11432240	|		|		|	
    221814	|	3600667	|	Leucocarbo georgianus	|	species	|	ncbi:732180,irmng:10664623	|		|		|	
    3600651	|	3600667	|	Leucocarbo melanogenis	|	species	|	ncbi:1522879,gbif:6095258	|		|		|	
    480890	|	3600667	|	Leucocarbo chalconotus	|	species	|	ncbi:146625,worms:343941,gbif:5789268,irmng:10216391	|		|		|	
    3600650	|	3600667	|	Leucocarbo nivalis	|	species	|	ncbi:1522881,gbif:6095257	|		|		|	
    3600687	|	3600667	|	Leucocarbo verrucosus	|	species	|	ncbi:1522882,worms:343957,gbif:6066497,irmng:10456104	|		|		|	
    9834	|	3600667	|	Leucocarbo bougainvillii	|	species	|	ncbi:146616,worms:343938,gbif:6066498,irmng:11035289	|		|		|	
    323108	|	3600667	|	Leucocarbo magellanicus	|	species	|	ncbi:146620,worms:225945,gbif:2481856,irmng:10798454	|		|		|	
    31566	|	3600667	|	Leucocarbo ranfurlyi	|	species	|	ncbi:732179,worms:343954,gbif:4848928,irmng:10460887,irmng:11444082	|		|		|	
    401967	|	3600667	|	Leucocarbo bransfieldensis	|	species	|	ncbi:732181,irmng:11164885	|		|		|	
    9831	|	3600667	|	Leucocarbo campbelli	|	species	|	ncbi:146613,worms:225922,gbif:4848925,irmng:11266741,irmng:10438862	|		|		|	
    3600684	|	3600667	|	Leucocarbo carunculatus	|	species	|	ncbi:1522878,worms:225993,gbif:4848924,irmng:10442841,irmng:10456105	|		|		|	
    31563	|	3600667	|	Leucocarbo colensoi	|	species	|	ncbi:732178,worms:226050,gbif:4848923,irmng:11427210,irmng:10443126	|		|		|	
    9839	|	3600667	|	Leucocarbo purpurascens	|	species	|	ncbi:146619,gbif:5844188	|		|		|	
    446659	|	3600667	|	Leucocarbo atriceps	|	species	|	ncbi:555309,worms:225759,gbif:4848927,irmng:11138363,irmng:11432441	|		|		|	
    969843	|	3600667	|	Leucocarbo albiventer	|	species	|	ncbi:9208,gbif:6066499,irmng:10763189	|		|		|	
    bash-3.2$ 
    bash-3.2$ grep Leucocarbo tax/ott/synonyms.tsv 
    Phalacrocorax carunculatus colensoi	|	31563	|		|	Phalacrocorax carunculatus colensoi (synonym for Leucocarbo colensoi)	|	
    Phalacrocorax carunculatus chalconotus	|	480890	|		|	Phalacrocorax carunculatus chalconotus (synonym for Leucocarbo chalconotus)	|	
    Notocarbo melanogenis	|	3600651	|		|	Notocarbo melanogenis (synonym for Leucocarbo melanogenis)	|	
    Phalacrocorax magellanicus	|	323108	|		|	Phalacrocorax magellanicus (synonym for Leucocarbo magellanicus)	|	
    Nesocarbo campbelli	|	9831	|		|	Nesocarbo campbelli (synonym for Leucocarbo campbelli)	|	
    Leucocarbo atriceps georgianus	|	221814	|		|	Leucocarbo atriceps georgianus (synonym for Leucocarbo georgianus)	|	
    Leucocarbo purpuracens	|	9839	|		|	Leucocarbo purpuracens (synonym for Leucocarbo purpurascens)	|	
    Leucocarbo aristotelis	|	1021952	|		|	Leucocarbo aristotelis (synonym for Gulosus aristotelis)	|	
    Phalacrocorax melanogenis	|	3600651	|		|	Phalacrocorax melanogenis (synonym for Leucocarbo melanogenis)	|	
    Phalacrocorax atriceps	|	446659	|		|	Phalacrocorax atriceps (synonym for Leucocarbo atriceps)	|	
    Phalacrocorax nivalis	|	3600650	|		|	Phalacrocorax nivalis (synonym for Leucocarbo nivalis)	|	
    Eulococarbo colensoi	|	31563	|		|	Eulococarbo colensoi (synonym for Leucocarbo colensoi)	|	
    Notocarbo atriceps georgianus	|	221814	|		|	Notocarbo atriceps georgianus (synonym for Leucocarbo georgianus)	|	
    Phalacrocorax purpurascens	|	9839	|		|	Phalacrocorax purpurascens (synonym for Leucocarbo purpurascens)	|	
    Stictocarbo magellanicus	|	323108	|		|	Stictocarbo magellanicus (synonym for Leucocarbo magellanicus)	|	
    Phalacrocorax atriceps verrucosus	|	3600687	|		|	Phalacrocorax atriceps verrucosus (synonym for Leucocarbo verrucosus)	|	
    Phalacrocorax carunculatus	|	3600684	|		|	Phalacrocorax carunculatus (synonym for Leucocarbo carunculatus)	|	
    Leucocarbo punctatus	|	480891	|		|	Leucocarbo punctatus (synonym for Phalacrocorax punctatus)	|	
    Leucocarbo pelagicus	|	744568	|		|	Leucocarbo pelagicus (synonym for Urile pelagicus)	|	
    Phalacrocorax carunculatus onslowi	|	9837	|		|	Phalacrocorax carunculatus onslowi (synonym for Leucocarbo onslowi)	|	
    Phalacrocorax bransfieldensis	|	401967	|		|	Phalacrocorax bransfieldensis (synonym for Leucocarbo bransfieldensis)	|	
    Eulococarbo ranfurlyi	|	31566	|		|	Eulococarbo ranfurlyi (synonym for Leucocarbo ranfurlyi)	|	
    Phalacrocorax albiventer purpurascens	|	9839	|		|	Phalacrocorax albiventer purpurascens (synonym for Leucocarbo purpurascens)	|	
    Phalacrocorax bougainvillii	|	9834	|		|	Phalacrocorax bougainvillii (synonym for Leucocarbo bougainvillii)	|	
    Phalacrocorax chalconotus	|	480890	|		|	Phalacrocorax chalconotus (synonym for Leucocarbo chalconotus)	|	
    Leucocarbo nigrogularis	|	780772	|		|	Leucocarbo nigrogularis (synonym for Phalacrocorax nigrogularis)	|	
    Eulococarbo chalconotus	|	480890	|		|	Eulococarbo chalconotus (synonym for Leucocarbo chalconotus)	|	
    Eulococarbo onslowi	|	9837	|		|	Eulococarbo onslowi (synonym for Leucocarbo onslowi)	|	
    Phalacrocorax albiventor purpurascens	|	9839	|		|	Phalacrocorax albiventor purpurascens (synonym for Leucocarbo purpurascens)	|	
    Leucocarbo atriceps nivalis	|	3600650	|		|	Leucocarbo atriceps nivalis (synonym for Leucocarbo nivalis)	|	
    Phalacrocorax campbelli colensoi	|	31563	|		|	Phalacrocorax campbelli colensoi (synonym for Leucocarbo colensoi)	|	
    Leucocarbo albivente	|	969843	|		|	Leucocarbo albivente (synonym for Leucocarbo albiventer)	|	
    Phalacrocorax albiventer melanogenis	|	3600651	|		|	Phalacrocorax albiventer melanogenis (synonym for Leucocarbo melanogenis)	|	
    Phalacrocorax georgianus	|	221814	|		|	Phalacrocorax georgianus (synonym for Leucocarbo georgianus)	|	
    Notocarbo purpurascens	|	9839	|		|	Notocarbo purpurascens (synonym for Leucocarbo purpurascens)	|	
    Phalacrocorax ranfurlyi	|	31566	|		|	Phalacrocorax ranfurlyi (synonym for Leucocarbo ranfurlyi)	|	
    Phalacrocorax albiventer	|	969843	|		|	Phalacrocorax albiventer (synonym for Leucocarbo albiventer)	|	
    Phalacrocorax carunculatus campbelli	|	9831	|		|	Phalacrocorax carunculatus campbelli (synonym for Leucocarbo campbelli)	|	
    Phalacrocorax verrucosus	|	3600687	|		|	Phalacrocorax verrucosus (synonym for Leucocarbo verrucosus)	|	
    Notocarbo atriceps	|	446659	|		|	Notocarbo atriceps (synonym for Leucocarbo atriceps)	|	
    Phalacrocorax onslowi	|	9837	|		|	Phalacrocorax onslowi (synonym for Leucocarbo onslowi)	|	
    Notocarbo georgianus	|	221814	|		|	Notocarbo georgianus (synonym for Leucocarbo georgianus)	|	
    Eulococarbo carunculatus	|	3600684	|		|	Eulococarbo carunculatus (synonym for Leucocarbo carunculatus)	|	
    Phalacrocorax colensoi	|	31563	|		|	Phalacrocorax colensoi (synonym for Leucocarbo colensoi)	|	
    Notocarbo verrucosus	|	3600687	|		|	Notocarbo verrucosus (synonym for Leucocarbo verrucosus)	|	
    Leucocarbo capensis	|	9836	|		|	Leucocarbo capensis (synonym for Phalacrocorax capensis)	|	
    Phalacrocorax campbelli	|	9831	|		|	Phalacrocorax campbelli (synonym for Leucocarbo campbelli)	|	
    bash-3.2$

**Comment by jar398** [comment]
@mtholder Please review and close if satisfied

**Comment by jar398** [comment]
No response from @mtholder so closing. Feel free to re-open.
