### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/reference-taxonomy#155]
The following files are [listed](https://github.com/OpenTreeOfLife/reference-taxonomy/blob/2.9draft8-finishing-up/doc/ott2.9.md) as being in the ott download, but are currently missing:

1. differences.tsv
2. otu_differences.tsv
3. hidden.tsv

Also, the doc mentions "version.tsv", but this should be "version.txt".

**Comment by jar398** [comment]
On Thu, Aug 6, 2015 at 9:07 AM, Joseph W. Brown <notifications@github.com>
wrote:

> The following files are listed
> <https://github.com/OpenTreeOfLife/reference-taxonomy/blob/2.9draft8-finishing-up/doc/ott2.9.md>
> as being in the ott download, but are currently missing:
>
>    1. differences.tsv
>    2. otu_differences.tsv
>    3. hidden.tsv
>
> Do you use these files? I removed them because they are very big and they
were not useful to me. Also they are easily regenerated using smasher. If
you need them, maybe I will make them into a separate download.

**Comment by josephwb** [comment]
No, don't need them. The doc just lists mthat they will be present. I guess this is just an issue of updating the doc(s).

**Comment by josephwb** [comment]
I updated both docs [1](http://files.opentreeoflife.org/ott/ott2.9/) and [2](https://github.com/OpenTreeOfLife/reference-taxonomy/blob/2.9draft8-finishing-up/doc/ott2.9.md).
