### ISSUE TITLE
Improve SILVA/NCBI alignment

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/reference-taxonomy#167]
See https://groups.google.com/d/msg/opentreeoflife/L2x3Ond16c4/9sbVO7htCgAJ

**Comment by jar398** [comment]
Still not fixed.  From @hyanwong:

5261710	|	702848	|	Daphnia pulex (common water flea)	|	no rank - terminal	|	ncbi:6669,silva:ACJG01014252	|	|
59086	|	59084	|	Daphnia pulex	|	species	|	ncbi:6669,worms:148375,gbif:2234840,irmng:10236269,irmng:10460016	|	|

734138	|	187951	|	Philaster apodigitiformis	|	species	|	ncbi:1198315	|	|	|	
533725	|	187951	|	Philaster digitiformis	|	species	|	ncbi:1198315,silva:FJ648350,ncbi:669200,worms:417453,gbif:5840067

**Comment by jar398** [comment]
By the way, this is a duplicate of #36

**Comment by hyanwong** [comment]
On 13 Oct 2015, at 17:21, Jonathan A Rees <notifications@github.com> wrote:

> By the way, this is a duplicate of #36

I guess my suggestion of labelling them ncbi_via_silva: in the taxonomy file is considered too much of a hack?

Yan

**Comment by jar398** [comment]
The problem of multiple records with the same NCBI id is fixed, I believe.

The problem of sample misidentification in NCBI is much better than it was, but I cannot say I've found all cases. (They would generally show up as weird homonyms.) There is a manually maintained list of about 40 misnamed clusters / taxa; these get renamed to "cluster JX888097" or something similar.

I'm going to close this. Let me know if you see any more irregularities.
