### ISSUE TITLE
Add a modern mammal list to OTT

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/reference-taxonomy#177]
I think that https://github.com/OpenTreeOfLife/feedback/issues/157 is the tip of the iceberg.

The latest edition of [MSW](http://www.departments.bucknell.edu/biology/resources/msw3/) seems from 2005, so we probably already have it via GBIF.  Need something more recent. As of 2012 MSW 4th edition is "[currently being compiled](http://vertebrates.si.edu/msw/mswcfapp/msw/about.cfm)" - that's all I could find out about it on the web.

Terms of use for IUCN and CoL rule out using them. I wonder what VTO uses. @balhoff ?

**Comment by balhoff** [comment]
We only have NCBI for mammals, unfortunately.

**Comment by jar398** [comment]
I don't think that leaving an issue open for this is doing any good. I can't think of anything to do about this for now and it is certainly something we won't forget about. So I will close it.
