### ISSUE TITLE
source info for synonyms

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/reference-taxonomy#185]
I was trying to troubleshoot: https://github.com/OpenTreeOfLife/feedback/issues/194

In my copy of the ott2.9draft12 dir:

    $ grep -r Osteichthyes .
    ./synonyms.tsv:Osteichthyes	|	773483	|		|	Osteichthyes (synonym for Actinopterygii)	|	

which makes it hard (for me) to tell where that synonymy is coming from.

**Comment by jar398** [comment]
Yes, this deficiency was mentioned in a comment on #113 . #113 and this issue should be done together since they share about 99% of their implementation.

**Comment by jar398** [comment]
Fixed in 42cff74. There is now (2.10draft2) a 'source' column that tells you where the synonym came from.

**Comment by jar398** [comment]
See OpenTreeOfLife/taxomachine#142
