### ISSUE TITLE
bug in conflict service

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/reference-taxonomy#217]
See comment at 5:52 AM Central time 2 Sept.  on https://gitter.im/OpenTreeOfLife/public
I'm not seeing how to permalink a comment on gitter
Tylosaurus is a good search term.

**Comment by jar398** [comment]
1. Tylosaurus = Tylosurus is a taxonomy error that I will fix.

2. The conflict service ignores taxa that will be suppressed in synthesis.

**Comment by mtholder** [comment]
See https://github.com/OpenTreeOfLife/reference-taxonomy/issues/218
