### ISSUE TITLE
Suppress synonyms that have same name-string as accepted?

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/reference-taxonomy#219]
At some point @mtholder requested that the taxonomy synonyms.tsv file *not* contain any rows where the name is the same as the name ('accepted' name) of a taxon.

I implemented this in OTT 2.9, but did so in a buggy way that led to all sorts of problems. I undid that change for 2.10. Although I could implement the change in the way the synonyms.tsv file is written, I would like to keep those extra synonyms in the taxonomy file because they are valuable information for synthesis, and could conceivably be useful to curators.

If we are to do this, I think the correct approach is as a separate script that turns a synonyms.tsv file containing these synonyms into one that doesn't.

Is this worth doing, or can they simply be ignore but all the affected clients?

**Comment by mtholder** [comment]
I don't recall my reason for requesting that. So I think that we should do as you suggest. If my reason ever occurs to me, then I'll implement the filtering of the synonyms file. It is fine with me if we close this.
