### ISSUE TITLE
better example for lineage heuristic

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/reference-taxonomy#272]
For `Lineage` under [Alignment heuristics](https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/doc/method/method-details.md#alignment-heuristics), we could use a better example. Current example is: 

"Hyphodontia quercina in irmng aligns with Hyphodontia quercina in IF, not Malacodon candidus"

which a) doesn't illustrate the lineage and b) the simple name-matching makes the lineage reasoning seem unnecessary.

**Comment by jar398** [comment]
Plasmodiophora diplantherae
Source node = if:529656 (in Phytomyxea in Opisthokonta), candidates = ncbi:1484321 (in Phytomyxea) and worms:172141 (in SAR)
The two candidates have different authorities (I looked them up) so I think they really are different beasts, and the correct choice was made. (The genus is not in the hemihomonym database, though, which creates doubt about their being different.)
Now to write it up

**Comment by jar398** [comment]
Review at https://github.com/OpenTreeOfLife/reference-taxonomy/commit/99af5b1e6adfaa431175e95867cae1dd221f9c91
or in current version of mss.
