### ISSUE TITLE
need example for Overlap alignment

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/reference-taxonomy#273]
For Overlap under [Alignment heuristics](https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/doc/method/method-details.md#alignment-heuristics), we need an example.

**Comment by jar398** [comment]
https://github.com/OpenTreeOfLife/reference-taxonomy/commit/31f4e057a3192c5084488a791f619ff1fdfbd90e
Part of PR #277
