### ISSUE TITLE
need Proximity alignment example

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/reference-taxonomy#274]
For Proximity under [Alignment heuristics](https://github.com/OpenTreeOfLife/reference-taxonomy/blob/master/doc/method/method-details.md#alignment-heuristics), we need an example.

**Comment by jar398** [comment]
Commit https://github.com/OpenTreeOfLife/reference-taxonomy/commit/f87c77f913a946b03c22f95e76527b05e93d6ad3
Part of PR #277
