### ISSUE TITLE
entries in 2.4 synonyms file

### ISSUE THREAD

**Issue by rhr** [OpenTreeOfLife/reference-taxonomy#32]
There are lines that start with ncbi:XXXX, e.g.:

ncbi:626292	|	838960	|		|	ncbi:626292 (synonym for Allochromatium sp. MT6010)	|	

Are labels of the form ncbi:XXXX intended to be synonyms of the NCBI name?

**Comment by jar398** [comment]
Hoping this will be fixed by #123
