### ISSUE TITLE
it would be nice to show ranked list of taxonomy for each taxon

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/reference-taxonomy#328]
lots of users would like to know the order that is relevant for each taxon.

**Comment by jar398** [comment]
Can you expand on this a little?

Not sure if this is what you're asking, but the source of each taxon is the first source in the list of sources. So if it says ncbi:xx, gbif:yy that means the taxon came from NCBI.

**Comment by mtholder** [comment]
Neither @kcranston  or I knew that. So I think we can close this as "done"
