### ISSUE TITLE
non-unique names in 2.5.draft1

### ISSUE THREAD

**Issue by rhr** [OpenTreeOfLife/reference-taxonomy#37]
5279946 Calothrix (genus in family Rivulariaceae)
12832 Calothrix (genus in family Rivulariaceae)
339002 Chlorella (genus in family Chlorellaceae)
5288014 Chlorella (genus in family Chlorellaceae)
5248842 Myrmecia (genus in order Microthamniales)
5282115 Myrmecia (genus in order Microthamniales)

**Comment by jar398** [comment]
Looks like these are all fixed now
