### ISSUE TITLE
Fungal orders from Hibbett 2007 are hidden in OTT 2.5 (no descendants)

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/reference-taxonomy#40]
There is no conflict in any of the following taxa between Hibbett 2007 updated taxonomy-tree currently store at figshare and Index fungorum

(1) Neozygitales - no conflict
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=564380

(2) Asterinales - no conflict
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=90461

(3) Urocystales = Urocystidales ---- OK I was able to map the synonym

(4) Savoryellales - no conflict

http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=561070
http://www.mycobank.org/Biolomics.aspx?Table=Mycobank&Page=200&ViewMode=Basic

(5) Cladochytriales - no conflict
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=512001

(6) Jaapiales - no conflict
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=515500

(7) Rhizocarpales - no conflict
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=529144

(8) Coniocybales - no conflict
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=800965

(9) Hyaloraphidiales - no conflict

http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=585034

(10) Mytilinidiales - no conflict

http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=511989

**Comment by jar398** [comment]
The 2015 revision of Hibbett 2007 is in OTT 2.9. I'm waiting for some family/order assignments from Romina.

**Comment by jar398** [comment]
Have received most assignments; still missing about 3 orders. This situation is actively monitored in the OTT build process so I think there's no need to keep this issue open.
