### ISSUE TITLE
deprecate Saxo-Fridericia (3965345) and Saxo-fridericia (5325529)

### ISSUE THREAD

**Issue by rhr** [OpenTreeOfLife/reference-taxonomy#50]
Perhaps create Saxo-fridericia synonym with Saxofridericia (221755)

**Comment by jar398** [comment]
Fixed in 2.8

**Comment by kcranston** [comment]
Reversing this suggested synonomy, as it appears that Saxo-fridericia is the accepted name according to [ncbi](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=142438), [irmng](http://www.irmng.org/aphia.php?p=taxdetails&id=1071613), and [gbif](https://www.gbif.org/species/2693294).
