### ISSUE TITLE
"mitosporic ascomycota"

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/reference-taxonomy#66]
Here are some revisions for the fungal part of the tree. Mitosporic groups have re-appeared and in many cases species nested under this group do have a place in the taxonomy (based on IF). Maybe these genera will be placed into their respective family/order once IF its updated. There is one case in which there is a species of Basidiomycota nested in "mitosporic ascomycota" #12 in this list. 

Notes – April 21, 2014. Fungal Tree/synthesis. “Mitosporic Ascomycota” revision

1.	Gloeosporium is under mitosporic Ascomycota and should be under Dermateaceae, Helotiales, Leotiomycetidae, Leotiomycetes, Pezizomycotina, Ascomycota, Fungi
2.	Marssonia is under mitosporic Ascomycota and should be under Dermateaceae, Helotiales, Leotiomycetidae, Leotiomycetes, Pezizomycotina, Ascomycota, Fungi
3.	Acremonium is under mitosporic Ascomycota and should be under Hypocreales, Hypocreomycetidae, Sordariomycetes, Pezizomycotina, Ascomycota, Fungi
4.	Dendrosporium is under mitosporic Ascomycota and should be under Pezizomycotina (there is no other classification)
5.	Dischloridium is under mitosporic Ascomycota – many species have been transferred to other genera, synonyms are in IF. This genus should be under Chaetosphaeriaceae, Chaetosphaeriales, Sordariomycetidae, Sordariomycetes, Pezizomycotina, Ascomycota, Fungi
6.	Eladia is under mitosporic Ascomycota and should be under Trichocomaceae, Eurotiales, Eurotiomycetidae, Eurotiomycetes, Pezizomycotina, Ascomycota, Fungi
7.	Macrophoma is under mitosporic Ascomycota and should be under Botryosphaeriaceae, Botryosphaeriales, Incertae sedis, Dothideomycetes, Pezizomycotina, Ascomycota, Fungi
8.	Cordana is under mitosporic Ascomycota and should be under Pezizomycotina
9.	Nakataet is under mitosporic Ascomycota and should be under Magnaporthaceae, Incertae sedis, Sordariomycetidae, Sordariomycetes, Pezizomycotina, Ascomycota, Fungi
10.	Phialacocephala is under mitosporic Ascomycota and should be under Helotiales, Leotiomycetidae, Leotiomycetes, Pezizomycotina, Ascomycota, Fungi. Species under this genus have been transferred to other genera under two families but from the same order Helotiales.
11.	Pseudofusarium us under mitosporic Ascomycota and should be under Nectriaceae, Hypocreales, Hypocreomycetidae, Sordariomycetes, Pezizomycotina, Ascomycota, Fungi
12.	Tricellulortus peponiformis (=Minimedusa obcoronata) is under mitosporic Ascomycota and should be under Basidiomycota Incertae sedis, Cantharellales, Incertae sedis, Agaricomycetes, Agaricomycotina, Basidiomycota, Fungi
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=414303

------------------------------------------------------------------------------------------------------------
•	The case of Tritirachium is very confusing, since many of the species under this genus have been transferred to genera that should be under Ascomycota such as Beauveria and Verticillium BUT IF still has it classified under Basidiomycetes (Tritirachiaceae, Tritirachiales, Incertae sedis, Tritirachiomycetes, Pucciniomycotina, Basidiomycota, Fungi). This can be a source of conflict; maybe we should hide this genus and try to work on its classification later.
•	The only genus – from the ones that are currently under “mitosporic Ascomycota”, only Sclerotium could be considered as fungi incertae sedis. This is a very old genus and the species described under have been transferred to genera distributed in very distant fungal groups (some even to Basidiomycota).

**Comment by jar398** [comment]
Need to check all of these against our July dump of Index Fungorum.

**Comment by jar398** [comment]
@rgazis I cannot find Nakataet or Phialacocephala in OTT at all or any of our other sources, so can't do anything about them.

**Comment by jar398** [comment]
@rgazis 
Gloeosporium comes from NCBI and is placed as follows:
	(75019=ncbi:446931+7 Gloeosporium?) << (971709=h2007:46+2289 Pezizomycotina) < (1098854=ncbi:716545+4 saccharomyceta) < (439373=h2007:40+2710 Ascomycota) < (656316=h2007:27+6 Dikarya) < (5582935=h2007:11+2 h2007-1) < (5575092=h2007:2+2 h2007-2) < (352914=silva:D11377/#4+11690 Fungi) < (5246132=silva:D11377/#3+4 Nucletmycea) < (332573=silva:D11377/#2+7 Opisthokonta) ...

Correct placement does not come from the version of IF that we have.  We can do ad-hoc surgery to make the taxonomy look as you prefer, but I'd rather put the effort into getting a new version of IF.

Similarly Dischloridium:
	(895423=ncbi:409208+2 Dischloridium?) < (737940=ncbi:103886+85 Chaetosphaeriaceae) < (778723=h2007:174+28 Chaetosphaeriales) < (921280=h2007:140+924 Sordariomycetes) < (5291459=h2007:77+5 Sordariomyceta) < (5287301=h2007:52+27 Leotiomyceta) < (971709=h2007:46+2289 Pezizomycotina) < (1098854=ncbi:716545+4 saccharomyceta) < (439373=h2007:40+2710 Ascomycota) < (656316=h2007:27+6 Dikarya) ...

All the others you list pass the tests I set up for them, but I could have screwed up in setting up the tests, so they should probably be examined again after OTT 2.9 is out.

**Comment by jar398** [comment]
In OTT 2.9draft12, Gleosporium has moved:

(176780=if:8849+814 Marssonina) < (832035=if:80686+117 Dermateaceae) < (51652=h2007:199+752 Helotiales) < (5344705=if:90517+11 Leotiomycetidae) < (346134=h2007:141+301 Leotiomycetes) < (5291459=h2007:77+5 Sordariomyceta) < (5287301=h2007:52+27 Leotiomyceta) < (971709=h2007:46+2039 Pezizomycotina) < (439373=h2007:40+2645 Ascomycota) < (5602101=h2007:27+8 Division=Dikarya) ...

This looks pretty good to me.

Dischloridium has become a synonym:
(946379=if:28644+18 Australiasca) < (5345436=if:515430+2 Australiascaceae) < (778723=h2007:174+28 Chaetosphaeriales) < (921280=h2007:140+1019 Sordariomycetes) < (5291459=h2007:77+5 Sordariomyceta) < (5287301=h2007:52+27 Leotiomyceta) < (971709=h2007:46+2039 Pezizomycotina) < (439373=h2007:40+2645 Ascomycota) < (5602101=h2007:27+8 Division=Dikarya) < (5584405=h2007:11+2 h2007-1) ...

This also looks pretty good. May be time to close this issue?
