### ISSUE TITLE
mitosporic basidiomycota + one algae lineage nested under Basidiomycota

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/reference-taxonomy#67]
Chlamydotomus (nested directly under Basidiomycota) is not considered to be fungi, but algae 

http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=164232

----------------------------------------------------------------------------------------------------------
In the tree Rhodorotula is nested within mitosporic basidiomycota BUT IF classifies it under Incertae sedis, Sporidiobolales, Incertae sedis, Microbotryomycetes, Pucciniomycotina, Basidiomycota, Fungi
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=9741
Trichosporon appears as mitosporic basidiomycota but IF has this genus under Trichosporonaceae, Tremellales, Incertae sedis, Tremellomycetes, Agaricomycotina, Basidiomycota, Fungi
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=10296

**Comment by jar398** [comment]
Here's what OTT 2.8 has for Chlamydotomus:

Chlamydotomus(5341855)
 genus size:2
	Basidiomycota(634628)  << Dikarya(656316)  << Fungi(352914)  << Nucletmycea(5246132)  << Opisthokonta(332573)  << Eukaryota(304358)  << cellular organisms(93302)  << life(805080) 
	 Chlamydotomus cellaris(4107529) species
Sources: if:22082,gbif:7258554,irmng:1069342
Flags: incertae_sedis,sibling_higher,sibling_lower

That is, in this case I believe Mycobank over Index Fungorum.  Is this OK?
