### ISSUE TITLE
Synonym information lost from IF to OTT2.8? (FUNGI)

### ISSUE THREAD

**Issue by rgazis** [OpenTreeOfLife/reference-taxonomy#84]
Hi

*based on tree @ http://devtree.opentreeoflife.org/opentree/argus/otol.draft.22@127
which contains OTT 2.8 

It seems that there are an excess of children (terminals) for many fungal genera. I looked into Lentinus which in our synthetic tree has 432 associated terminals (BTW I got this number 2 weeks ago but now the number of "terminal taxa within this clade" does not appear when browsing the tree or pressing the ?). In Index fungorum there are 628 records associated with this genus. So I guess there are a lot of "name resolution" during synthesis. However, I have the impression that we are loosing some information about synonyms which is contributing to the inflated numbers. 

So I have checked the 50 first terminals under Lentinus (http://devtree.opentreeoflife.org/opentree/otol.draft.22@213836/Lentinus) and found that for some of them the synonym info is in the IF version we are currently using but both names (the current name and the synonym is kept in the synthetic tree) 

Lentinus alpakus	
NO in IF / NO in NCBI taxonomy	
in IF = Lentinus alpacus	
misspelling but link to IF Idtaxa goes to the correct spelling L. alpacus

Lentinus atrolucidus	
In IF Hohenbuehelia atrolucida	
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=257745	
not in the IF we are using in OTT2.8

Lentinus barguirmiensis	
not in IF or NCBI	
GBIF: 3363900	
coming from GBIF

Lentinus battarrae	
In IF Psathyrella battarrae	
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=469658	
In the IF we are using in OTT2.8

Lentinus begurensis	
name invalid in IF	
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=548489	

Lentinus berkeleyi	
In IF Elmerina berkeleyi	
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=469659	
In the IF we are using in OTT2.8

Lentinus berterii	
In IF Lentinus berteroi 	
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=580950	Ortographic variant

Lentinus bertieri	
In IF Lentinus berteroi 		
Ortographic variant

Lentinus bonariensis	
In IF Lentinus bonaerensis 	
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=587291	Ortographic variant

Lentinus caespiticola	
In IF Panus caespiticola	
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=190991	
In the IF we are using in OTT2.8

Lentinus caespitosus	
In IF Lentinus squarrosulus	
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=165075	
In the IF we are using in OTT2.8

Lentinus carneotomentosus	
In IF Panus conchatus	
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=469661	
In the IF we are using in OTT2.8

Lentinus citrinus	
not in IF or NCBI	
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=315762	
GBIF: 3364106

Lentinus clitocyboides	
In IF Russula clitocyboides	
http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=154031

**Comment by jar398** [comment]
Anything left to be done on this?  Assigning to @pmidford so he can answer that question and (I hope) close the issue

**Comment by pmidford** [comment]
Definitely need to decide what to do about GBIF names that aren't otherwise supported - several of the GBIF only names cite (outdated?) IF.  Also need to try to distinguish IF from SF, for example: L. caespiticola vs. Panus caespiticola - both present in OTT (SF indicates L. caespiticola as basionym, IF does not indicate synonymy of L. caespiticola).  But these (IF vs. SF, GBIF vs. specific taxonomy resources) general issues are known, not specific to this genus.  So, I'd say nothing special to be done here - I say ok to close.
