### ISSUE TITLE
Consolidate release-information into one location?

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/reference-taxonomy#96]
It's currently scattered around the wiki, NEWS.md, etc.

**Comment by jar398** [comment]
I think this is better now; the wiki points to the doc/ directory, which has a release notes file for each release, and there is no NEWS.md as far as I know. 

@jimallman, if it looks ok, please close the issue.

**Comment by jimallman** [comment]
Much better, thanks!
