### ISSUE TITLE
match_taxa mistake: P. maniculatus (mouse) --> Odontocarus maniculatus (tick)

### ISSUE THREAD

**Issue by arlin** [OpenTreeOfLife/reference-taxonomy#99]
using version 2 match_names (devapi.opentreeoflife.org/v2/tnrs/match_names) with  {"context":"Mammals", "names":["Peromyscus maniculatus"]} and I'm getting "Odontacarus maniculatus" as a synonym.  One problem is that this is a actually a parasite of P. manuculatus, not the same thing, and the other problem is that it's not a mammal species but a tick, and I was using context restriction "Mammals". 

Here is the complete return from match_names: 

{
"governing_code":"ICZN",
"unambiguous_name_ids":[
"Peromyscus maniculatus"
],
"unmatched_name_ids":[
],
"matched_name_ids":[
"Peromyscus maniculatus"
],
"context":"Mammals",
"includes_deprecated_taxa":false,
"includes_dubious_names":false,
"includes_approximate_matches":true,
"taxonomy":{
"author":"open tree of life project",
"weburl":"https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-Taxonomy",
"source":"ott2.8"
},
"results":[
{
"id":"Peromyscus maniculatus",
"matches":[
{
"is_deprecated":false,
"is_synonym":false,
"flags":[
],
"search_string":"peromyscus maniculatus",
"score":1.0,
"synonyms":[
"North American deer mouse",
"Peromyscus maniculatus",
"Peromyscus maniculatis"
],
"is_approximate_match":false,
"ot:ottId":377525,
"matched_node_id":3545448,
"rank":"",
"matched_name":"Peromyscus maniculatus",
"unique_name":"Peromyscus maniculatus (species in subfamily Neotominae)",
"is_dubious":false,
"nomenclature_code":"ICZN",
"ot:ottTaxonName":"Peromyscus maniculatus"
},
{
"is_deprecated":false,
"is_synonym":true,
"flags":[
"TATTERED_INHERITED"
],
"search_string":"peromyscus maniculatus",
"score":1.0,
"synonyms":[
"Odontacarus maniculatus",
"Peromyscus maniculatus"
],
"is_approximate_match":false,
"ot:ottId":5116122,
"matched_node_id":1181640,
"rank":"",
"matched_name":"Peromyscus maniculatus",
"unique_name":"Odontacarus maniculatus",
"is_dubious":false,
"nomenclature_code":"ICZN",
"ot:ottTaxonName":"Odontacarus maniculatus"
}
]
}
]
}

**Comment by jar398** [comment]
$ curl -X POST http://api.opentreeoflife.org/v2/tnrs/match_names -H "content-type:application/json" -d '{"context":"Mammals", "names":["Peromyscus maniculatus"]}'
    {
      "governing_code" : "ICZN",
      "unambiguous_name_ids" : [ "Peromyscus maniculatus" ],
      "unmatched_name_ids" : [ ],
      "matched_name_ids" : [ "Peromyscus maniculatus" ],
      "context" : "Mammals",
      "includes_deprecated_taxa" : false,
      "includes_dubious_names" : false,
      "includes_approximate_matches" : true,
      "taxonomy" : {
        "weburl" : "https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-Taxonomy",
        "author" : "open tree of life project",
        "source" : "ott2.9draft12"
      },
      "results" : [ {
        "id" : "Peromyscus maniculatus",
        "matches" : [ {
          "matched_node_id" : 2598487,
          "synonyms" : [ "Peromyscus maniculatus", "Peromyscus maniculatis" ],
          "flags" : [ ],
          "ot:ottTaxonName" : "Peromyscus maniculatus",
          "search_string" : "peromyscus maniculatus",
          "matched_name" : "Peromyscus maniculatus",
          "is_synonym" : false,
          "score" : 1.0,
          "unique_name" : "Peromyscus maniculatus",
          "ot:ottId" : 377525,
          "is_deprecated" : false,
          "nomenclature_code" : "ICZN",
          "is_approximate_match" : false,
          "rank" : "",
          "is_dubious" : false
        } ]
      } ]
    }

**Comment by arlin** [comment]
Thanks!  I tried it out and got the same thing.
